version: '3.9'

services:
  database:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - ./db:/tmp/db:rw

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '3000:3000'
    volumes:
      - .:/rails
    env_file:
      - .env.development
    stdin_open: true
    tty: true
